allContracts: true

testMode: 'assertion'
coverage: true
corpusDir: 'corpus-echidna'

workers: 3
seqLen: 100
testLimit: 100000

balanceContract: 1000000000000000000000000 # 100 ether

rpcUrl: 'https://arb-mainnet.g.alchemy.com/v2/3SkKWYW6eyZV1DvJIEIKfdY99xWS1U-P'
rpcBlock: 195078119

codeSize: 0xfffffffffff # increase the code size
testMaxGas: 1250000000 # increases test max gas for future complex operations
